package ml.zedlabs.data.local_db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import ml.zedlabs.domain.model.common.MediaType

@Entity
data class AddedList(
    //id generated for our app
    @PrimaryKey(autoGenerate = true) val mediaId: Int = 0,
    //id generated by backend
    @ColumnInfo(name = "media_id") val uid: Int,
    @ColumnInfo(name = "media_name") val title: String?,
    @ColumnInfo(name = "media_desc") val description: String?,
    @ColumnInfo(name = "poster_path") val posterPath: String?,
    @ColumnInfo(name = "type") val type: MediaType,
)
